//Códigos de interpretación de tiempo
export const weatherCodeMap = {
  0: ["Cielo despejado", "assets/images/icon-sunny.webp"],
  1: ["Mayormente despejado", "assets/images/icon-sunny.webp"],
  2: ["Parcialmente nublado", "assets/images/icon-partly-cloudy.webp"],
  3: ["Cubierto", "assets/images/icon-partly-cloudy.webp"],
  45: ["Niebla", "assets/images/icon-partly-cloudy.webp"],
  48: ["Niebla de escarcha", "assets/images/icon-fog.webp"],
  51: ["Llovizna ligera", "assets/images/icon-drizzle.webp"],
  53: ["Llovizna moderada", "assets/images/icon-drizzle.webp"],
  55: ["Llovizna densa", "assets/images/icon-drizzle.webp"],
  56: ["Llovizna helada ligera", "assets/images/icon-drizzle.webp"],
  57: ["Llovizna helada densa", "assets/images/icon-drizzle.webp"],
  61: ["Lluvia ligera", "assets/images/icon-rain.webp"],
  63: ["Lluvia moderada", "assets/images/icon-rain.webp"],
  65: ["Lluvia intensa", "assets/images/icon-rain.webp"],
  66: ["Lluvia helada ligera", "assets/images/icon-rain.webp"],
  67: ["Lluvia helada densa", "assets/images/icon-rain.webp"],
  71: ["Nieve ligera", "assets/images/icon-snow.webp"],
  73: ["Nieve moderada", "assets/images/icon-snow.webp"],
  75: ["Nieve intensa", "assets/images/icon-snow.webp"],
  77: ["Granos de nieve", "assets/images/icon-snow.webp"],
  80: ["Lluvias ligeras", "assets/images/icon-rain.webp"],
  81: ["Lluvias moderadas", "assets/images/icon-rain.webp"],
  82: ["Lluvias fuertes", "assets/images/icon-rain.webp"],
  85: ["Luz de nieve ligera", "assets/images/icon-snow.webp"],
  86: ["Nevadas fuertes", "assets/images/icon-snow.webp"],
  95: ["Tormenta eléctrica", "assets/images/icon-storm.webp"],
  96: ["Tormenta eléctrica con granizo ligero", "assets/images/icon-storm.webp"],
  99: ["Tormenta eléctrica con granizo fuerte", "assets/images/icon-storm.webp"],
};

// Lista de ciudades sugeridas
export const predefinedCities = [
  { name: "Madrid", country: "Spain", lat: 40.4165, long: -3.7026 },
  { name: "New York", country: "United States", lat: 40.7143, long: -74.006 },
  { name: "Tokyo", country: "Japan", lat: 35.6895, long: 139.6917 },
  { name: "London", country: "United Kingdom", lat: 51.5085, long: -0.1257 },
  { name: "Paris", country: "France", lat: 48.8534, long: 2.3488 },
  { name: "Rome", country: "Italy", lat: 41.9028, long: 12.4964 },
  { name: "Berlin", country: "Germany", lat: 52.52, long: 13.405 },
  { name: "Sydney", country: "Australia", lat: -33.8688, long: 151.2093 },
  { name: "Buenos Aires", country: "Argentina", lat: -34.6037, long: -58.3816 },
  { name: "Mexico City", country: "Mexico", lat: 19.4326, long: -99.1332 },
  { name: "Bogotá", country: "Colombia", lat: 4.711, long: -74.0721 },
  { name: "Cairo", country: "Egypt", lat: 30.0444, long: 31.2357 },
  { name: "Beijing", country: "China", lat: 39.9042, long: 116.4074 },
  { name: "Seoul", country: "South Korea", lat: 37.5665, long: 126.978 },
  { name: "Toronto", country: "Canada", lat: 43.651, long: -79.347 },
  { name: "Rio de Janeiro", country: "Brazil", lat: -22.9068, long: -43.1729 },
  { name: "Dubai", country: "United Arab Emirates", lat: 25.2048, long: 55.2708 },
  { name: "Mumbai", country: "India", lat: 19.076, long: 72.8777 },
];